import React, { useState } from 'react';
import { Copy, Download, FileText, Check, FileCode } from 'lucide-react';
import jsPDF from 'jspdf';
import type { ProcessedDocument, SummaryLength } from '../types';

interface ExportBarProps {
  document: ProcessedDocument;
  summaryLength: SummaryLength;
}

export const ExportBar: React.FC<ExportBarProps> = ({ document, summaryLength }) => {
  const [copied, setCopied] = useState(false);

  const getActiveSummaryText = (): string => {
    switch (summaryLength) {
      case 'short':
        return document.summary.shortSummary;
      case 'medium':
        return document.summary.mediumSummary;
      case 'long':
        return document.summary.longSummary;
    }
  };

  const handleCopy = () => {
    const textToCopy = getActiveSummaryText();
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    const content = `DOCUMENT SUMMARY REPORT: ${document.name}\n\nEXECUTIVE SUMMARY:\n${document.summary.executiveSummary}\n\n${summaryLength.toUpperCase()} SUMMARY:\n${getActiveSummaryText()}\n\nKEY TAKEAWAYS:\n${document.summary.keyPoints.map(kp => `- ${kp.text}`).join('\n')}\n`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document.name.replace(/\.[^/.]+$/, '')}_summary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadMd = () => {
    const content = `# Document Summary: ${document.name}

## Executive Summary
${document.summary.executiveSummary}

## ${summaryLength.toUpperCase()} Summary
${getActiveSummaryText()}

## Key Takeaways & Main Ideas
${document.summary.keyPoints.map(kp => `- **[${kp.category.toUpperCase()}]** ${kp.text}`).join('\n')}

## Writing & Readability Suggestions
${document.summary.improvementSuggestions.map(s => `- **${s.title}**: ${s.suggestion}`).join('\n')}

---
*Generated by DocuSummarize AI Assistant*
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document.name.replace(/\.[^/.]+$/, '')}_summary.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(30, 41, 59);
    doc.text('DocuSummarize AI - Document Report', 14, 20);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Source File: ${document.name}`, 14, 28);
    doc.text(`Generated: ${new Date().toLocaleDateString()} | Readability Score: ${document.summary.stats.readabilityScore}/100`, 14, 34);

    doc.setLineWidth(0.5);
    doc.setDrawColor(203, 213, 225);
    doc.line(14, 38, 196, 38);

    // Section 1: Executive Summary
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(79, 70, 229);
    doc.text('Executive Summary', 14, 48);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);

    const execLines = doc.splitTextToSize(document.summary.executiveSummary, 180);
    doc.text(execLines, 14, 56);

    let currentY = 56 + execLines.length * 6 + 6;

    // Section 2: Main Summary
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(79, 70, 229);
    doc.text(`${summaryLength.toUpperCase()} Summary`, 14, currentY);
    currentY += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);

    const mainLines = doc.splitTextToSize(getActiveSummaryText(), 180);
    doc.text(mainLines, 14, currentY);

    currentY += mainLines.length * 6 + 8;

    // Section 3: Key Points
    if (currentY < 240) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(79, 70, 229);
      doc.text('Key Points & Highlights', 14, currentY);
      currentY += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);

      document.summary.keyPoints.slice(0, 4).forEach((kp) => {
        if (currentY < 275) {
          const kpLines = doc.splitTextToSize(`• ${kp.text}`, 175);
          doc.text(kpLines, 16, currentY);
          currentY += kpLines.length * 5 + 3;
        }
      });
    }

    doc.save(`${document.name.replace(/\.[^/.]+$/, '')}_report.pdf`);
  };

  return (
    <div className="flex flex-wrap items-center justify-end gap-2 pt-2 border-t border-slate-800/80">
      
      {/* Copy Summary */}
      <button
        onClick={handleCopy}
        className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-all"
      >
        {copied ? (
          <>
            <Check className="h-3.5 w-3.5 text-emerald-400" />
            <span className="text-emerald-400">Copied!</span>
          </>
        ) : (
          <>
            <Copy className="h-3.5 w-3.5 text-indigo-400" />
            <span>Copy Text</span>
          </>
        )}
      </button>

      {/* Download Markdown */}
      <button
        onClick={handleDownloadMd}
        className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-all"
      >
        <FileCode className="h-3.5 w-3.5 text-purple-400" />
        <span>Export .MD</span>
      </button>

      {/* Download TXT */}
      <button
        onClick={handleDownloadTxt}
        className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-all"
      >
        <FileText className="h-3.5 w-3.5 text-cyan-400" />
        <span>Export .TXT</span>
      </button>

      {/* Download PDF */}
      <button
        onClick={handleDownloadPdf}
        className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-500/20 transition-all"
      >
        <Download className="h-3.5 w-3.5" />
        <span>Export PDF</span>
      </button>
    </div>
  );
};
